CREATE TABLE IF NOT EXISTS Biddings (
	BidID TEXT NOT NULL,
	UserID TEXT NOT NULL,
	Slot INTEGER NOT NULL,
	Bid INTEGER NOT NULL,
	AddedTS TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
)